language: java
dist: trusty
sudo: false
jdk:
- oraclejdk11
script:
- "./mvnw --settings .ci/settings.xml install -Dmaven.test.skip=true -Dgpg.skip -Dmaven.javadoc.skip=true
  -B -V -q"
before_install:
  - openssl aes-256-cbc -K $encrypted_01edcdfe89aa_key -iv $encrypted_01edcdfe89aa_iv -in .ci/secret.asc.enc -out .ci/secret.asc -d
install:
- "./mvnw --settings .ci/settings.xml install -Dmaven.test.skip=true -Dgpg.skip -Dmaven.javadoc.skip=true
  -B -V -q"
after_success:
- "./mvnw -pl '!spring-cloud-zuul-ratelimit-dependencies' clean org.jacoco:jacoco-maven-plugin:prepare-agent
  verify jacoco:report coveralls:report -q -Dlogging.level.root=ERROR"
cache:
  directories:
  - "$HOME/.m2/repository"
notifications:
  email:
  - marcos.hgb@gmail.com
  - lchayoun@gmail.com
deploy:
- provider: script
  script: bash .ci/deploy.sh
  skip_cleanup: true
  on:
    branch: master
    repo: marcosbarbero/spring-cloud-zuul-ratelimit
    jdk: oraclejdk11
env:
  global:
  - secure: NtNa5ECD5zk+9iTMPiH7yKCAWyiAwbX1bDDvgQSRySrd6HGatstMPW41PieZOGQGLwaXQ+E1x2CR9JdofQMLNaqifOhi3zEEd4FbYSwqPWrWbRrMppvWSszLGc3avRehVd2jcWlDWlAYPShdf446rje/sM0CdLtY0VUOgy9HLw70RSJMfTrmv2l0oBRQm9Klb4FanQDtMjmDNpHb2Z63EINccBVizUZchfcWPesoU1HV61L1c3KAsfSrDMvvsP0HDsJWGKPuVJJQbQ+PehoUZ4/avXaRSvxWO6pWZh4u7Y+3baYuhb5m65mHx0Qpc4g7Lk5O3iKO8pH+8/ILqUpphLkAFNgnqEfi3uTY9k+wzdIz8On39AKWh3EVcr3JlUvhnvqs3OqRCx6Cvm3r/GovhWSwf0z2mPG5RNfjkL1uxksQEHIBOOai9pP0aTPovPm8j10JG9hf7022P7wRaKBg1bMxS9f5EAe8h/hSxRMRgH/1X2s5Ky8OBYmuh8O0jOlv6jLDdK4/4ulLwnSN7+Vd9nEVLmHLQEiwkQo+6ZaeQv1nvRvg6NvZeVMKkmH8jdCx2qSs4Hsj99amwKoplPt+Z6rZ4AQVsqSFr6wSapR2XSy7ZtiMgv96PyDgHfwRUxfI3jJSsdXugoOjmwd6iTkcy6v4qcdyxd22HvPVKX9Jv8M=
  - secure: M5tkMVR0ZH6hbxn8wvJAwo9tRL5nlL0TswMoz2ziCtaKcYgQtKuNGJYfhP3HImcyKoRQuaYOBs7k0CqKEsa4XloeanywHDEXvY8d6ot8qd3HiinHGm3Cg6Q+tHt2CMMlkYP4HEVCZZUY08weU5iUBljrzd8WQJUhVaH4WlqfQ7vRCEot5VSQKMVuaRPMjZPonvS+IELyNPQx4/gxzSnHSFHRrmbOYhZqdZ2y2mLRhkRwZK6fvC5GhHqTUL3vnEGfkqgbXgQY5SWkZy7e0IFpXLD2YoiSCKlX2dAfoD/YbVvcHNnhD6maVE/xtOqfDbrlvgMoQx9wTME3TNCW5V0jTiePeYHCphMNcD5vGBKR0fZB/KvK0VOOPBwsbG6jFMZ5mzv3v48/ExD+E+hpqyh+GFPnFL4m5GSGY2+ZTeI0VUKu3egtCFlqAFZ/IyuijSD4pv09t5colTWU/D2mCGYsA6bJvMEhZuRh0v837s9GT16HF5cfoR3TvbWnqulLrmwjHX71fP/WzR2SiQIRVzOIJX29OtTed/iKe5Ps/Qjif43zlRLhLgOIima1xfzRIczl2h9yg0APUuuJku8M/vIUGNVjtddhM6s9ei3Uq4IRTPAKrxDOJqOqpBx8OviTN4S6TtxaW2i1112Z92QtJboeHyGRbHYXXLixl9VGHslKSz0=
  - secure: X5btfyUnqhdj5o278+QTSwMfZ8/hOBxM3YIwDPXkB6byNLFQlu4mBDxZX0PrR6JJvs6aQMJ0Jc6Qw9i6F34I1O/JdauH9z9Cw+TkmApX3cux8yzjrxBWJJuQ9vOEOQO4OwKm7tdPK+xOZJ0nrtpb1mVTVLyR/1vkxnRtjLKanaU/QC22iKM9PKuaB0GHA9PbrjYX5vQN+IAqc/ci1/tf3jgSsK/+No59Pv+yR8IJXMShsNc22aTIpGCjwgd8CocH36dFXF4MvxBf2bI314bmrr0FhOpNUZ5z/LiXDcTt0JqpR1BywKjJfhYb1M+TzaIvAs60oBTM7s3y1zF/krVt41zexXzvkONolXuHLXpU9EGwJ+60Kt9jzk/xtbThIrapzGvsSpIJLKRBI7M5nuMMhX6vIIsnIJs571eu6QAK84JoPdJ41x6gtK3b1LsJ4y9NnFX5Vs+KeDOaUnRxM/7EXbiJ4B4X7yRDjcxjtn1aPgy/gfL9Bj0j8tz/88mquQmgXpZ6bl0/kVUEs9d6qZSghifgl9b3r3oLZyP2ZvD5hEDbYraR+merwhCO7/bZyZqlLI7TRfwjHSABBzXggqOk3aumSkwYcnZlt4PkkwD7DNyve3rgD5bghiE1unL+rVJ/krlwXsus1Fd0mufi+wQpSuYR6y3G9+6sh02/Vk0U9j4=
  - secure: j8Xx5VQ5lC9S3yNtta7z9TcnwI69qGo85b4Xrc7KGN6v/bPmaZhsyMZzp39nVx5FqCzUHty0CGB3d3kHOFqluPIkjqBH/VKFddadYlu+AUVyvkDRSI0NS23nYo3zknH2X+r0FXCCR08s6lu0rpGlRHJAHtK3V5MN/Ki3Vqq620326u5CZliOX+v3VTvcv958svLWfNkoZRBKejJevyXY5IYknNaWn4fgtarEpODlci2g6eWpTsVGuC+w8YRLzfjwzEs0SCDtnZP3XUfSkSRrR8H1wHXqk7g8IsHOgWCQv+ubve82XkOUAym5g2Lh21QnQB1MzMuLm3mtqquP3dtpy8jxP0+7i22H+HalZx81qjNvw6EiY4+wTrJ4ah5c4wjB5obU8VLLo2gNa1qkE/GwCkGSLN6+JrK/pK4eEjw99Y3VEsdzVnjb3ITWZgcD4pzpyKwxTCSoRCUbrd66F1YULNGVUdgD+ZtUNk9itqOavbLFofY2g9RTdrfqUAKsj0d1XbzrpdO0xbx/t0CNND7GjHGmoERwapYDW98L+qycjBpTmAsN0+refe8HMNFHeOcGqlMgc6BLFqzwZzh1zqot8mqSOoyjSi/O8JOeO8CHOhuuc5i0fVqGVcYVfaaNdNwu3xjmsWnfjolj8F9YcxnsPM8ARe7/0dirKYxVP20nzKU=
